package storagehost

import (
	"errors"
	"fmt"
	"os"
)

// Allocator is §4.1's create-side component: given a server-authorized
// coord (already generated by the home's registry, §1.6 — this package
// never mints one itself), mkdir (dir=true) or touch (dir=false) it under
// the channel's live/ tree. Idempotent (§4.7: "mkdir 已存在=成功") — a
// replayed AllocRequest for the same coord is a clean no-op, never an
// error, so the door's synchronous content-less create path (§1.5) can
// retry safely.
type Allocator struct{}

// Alloc performs the mkdir/touch. dir selects MkdirAll (a directory-shaped
// create) vs a zero-length file (an empty regular file create) — the same
// two content-less shapes CreateSpec.Dir distinguishes at the door.
func (Allocator) Alloc(cr *channelRoot, coord string, dir bool) error {
	p, err := livePath(coord)
	if err != nil {
		return err
	}
	if dir {
		if err := cr.root.MkdirAll(p, 0o700); err != nil {
			return fmt.Errorf("storagehost: alloc mkdir %q: %w", coord, err)
		}
		return nil
	}
	// Touch: idempotent — an already-existing entry (file OR directory) at
	// this coord is left untouched (a replayed AllocRequest must not
	// truncate real content a first successful Alloc, or a subsequent
	// write, already landed).
	if _, err := cr.root.Stat(p); err == nil {
		return nil
	} else if !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("storagehost: alloc stat %q: %w", coord, err)
	}
	f, err := cr.root.Create(p)
	if err != nil {
		return fmt.Errorf("storagehost: alloc create %q: %w", coord, err)
	}
	return f.Close()
}
