package workapi

// These schemas describe the work-aware profile only. Actors that do not
// advertise CapabilityWorkProtocolV1 must keep publishing their legacy word
// schemas rather than presenting these fields and rejecting them at runtime.
const AskInputSchema = `{"type":"object","required":["text"],"properties":{"text":{"type":"string","minLength":1},"attachments":{"type":"array"},"origin":{"type":"object","required":["session"],"properties":{"session":{"type":"string","minLength":1},"label":{"type":"string"}},"additionalProperties":false},"delivery":{"enum":["wait","receipt"]},"submission_key":{"type":"string","minLength":1,"maxLength":256},"related_work_id":{"type":"string","minLength":1,"maxLength":256}},"allOf":[{"if":{"properties":{"delivery":{"const":"receipt"}},"required":["delivery"]},"then":{"required":["submission_key"]}}],"additionalProperties":false}`

const StatusInputSchema = `{"oneOf":[{"type":"object","properties":{"cursor":{"type":"string"},"limit":{"type":"integer","minimum":1,"maximum":100}},"additionalProperties":false},{"type":"object","required":["work_id"],"properties":{"work_id":{"type":"string","minLength":1,"maxLength":256}},"additionalProperties":false},{"type":"object","required":["submission_key"],"properties":{"submission_key":{"type":"string","minLength":1,"maxLength":256}},"additionalProperties":false}]}`

const ResultInputSchema = `{"type":"object","required":["work_id"],"properties":{"work_id":{"type":"string","minLength":1,"maxLength":256}},"additionalProperties":false}`

const SteerInputSchema = `{"oneOf":[{"type":"object","required":["text"],"properties":{"work_id":{"type":"string","minLength":1,"maxLength":256},"operation_key":{"type":"string","maxLength":256},"text":{"type":"string","minLength":1},"expected_turn_id":{"type":"string"}},"additionalProperties":false},{"type":"object","required":["target"],"properties":{"work_id":{"type":"string","minLength":1,"maxLength":256},"operation_key":{"type":"string","maxLength":256},"target":{"type":"string","minLength":1}},"additionalProperties":false},{"type":"object","required":["all"],"properties":{"work_id":{"type":"string","minLength":1,"maxLength":256},"operation_key":{"type":"string","maxLength":256},"all":{"const":true}},"additionalProperties":false}]}`

// WorkTextSteerInputSchema is the exact subset advertised by the native
// Controller. It remains the same agent.steer word; capability discovery says
// which operation forms a particular implementation accepts.
const WorkTextSteerInputSchema = `{"type":"object","required":["work_id","text"],"properties":{"work_id":{"type":"string","minLength":1,"maxLength":256},"text":{"type":"string","minLength":1},"operation_key":{"type":"string","maxLength":256}},"additionalProperties":false}`

const InterruptInputSchema = `{"type":"object","properties":{"work_id":{"type":"string","minLength":1,"maxLength":256},"operation_key":{"type":"string","maxLength":256}},"additionalProperties":false}`

const AskOutputSchema = `{"type":"object","required":["work_id"],"properties":{"status":{"type":"string"},"disposition":{"type":"string"},"work_id":{"type":"string"},"work_state":{"enum":["open","closed"]},"state":{"enum":["open","closed"]},"stage":{"type":"string"},"outcome":{"type":"string"},"result":{},"guidance":{"type":"string"},"next":{"type":"array","items":{"$ref":"#/$defs/next"}}},"$defs":{"next":{"type":"object","required":["word","payload"],"properties":{"word":{"type":"string"},"label":{"type":"string"},"payload":{"type":"object"}},"additionalProperties":false}},"additionalProperties":true}`

const StatusOutputSchema = `{"type":"object","properties":{"status":{"type":"string"},"work":{"$ref":"#/$defs/work"},"works":{"type":"array","items":{"$ref":"#/$defs/work"}},"next_cursor":{"type":"string"},"guidance":{"type":"string"},"next":{"type":"array","items":{"$ref":"#/$defs/next"}}},"$defs":{"work":{"type":"object","required":["work_id","state"],"properties":{"work_id":{"type":"string"},"state":{"enum":["open","closed"]},"stage":{"type":"string"},"outcome":{"type":"string"},"source_request_id":{"type":"string"},"submission_key":{"type":"string"},"related_work_id":{"type":"string"},"execution_state":{"type":"string"},"inputs":{"type":"array","items":{"type":"object","required":["input_id","seq","disposition"],"properties":{"input_id":{"type":"string"},"seq":{"type":"integer"},"disposition":{"enum":["accepted","assigned","included","rejected"]}},"additionalProperties":false}},"created_at":{"type":"integer"},"updated_at":{"type":"integer"},"session_id":{"type":"string"},"turn_id":{"type":"string"}},"additionalProperties":false},"next":{"type":"object","required":["word","payload"],"properties":{"word":{"type":"string"},"label":{"type":"string"},"payload":{"type":"object"}},"additionalProperties":false}},"additionalProperties":false}`

const ResultOutputSchema = `{"type":"object","required":["work_id","state"],"properties":{"status":{"type":"string"},"work_id":{"type":"string"},"state":{"enum":["open","closed"]},"outcome":{"type":"string"},"result":{},"guidance":{"type":"string"},"next":{"type":"array","items":{"type":"object","required":["word","payload"]}},"session_id":{"type":"string"}},"additionalProperties":false}`

const ControlOutputSchema = `{"type":"object","properties":{"disposition":{"type":"string"},"work_id":{"type":"string"},"input_id":{"type":"string"},"included":{"type":"boolean"},"execution_state":{"type":"string"},"scope":{"type":"string"},"stop_requested":{"type":"integer"}},"oneOf":[{"required":["disposition"]},{"required":["scope","stop_requested"]}],"additionalProperties":true}`
